### ISSUE TITLE
Try to run the tests got error  "Unable to verify origin" for test script

### ISSUE THREAD

**Issue by afridi26** [duo-labs/py_webauthn#46] opened 2019-07-17 17:17 UTC
Hi,

When I try to test the library with the given webauthn_test.py. I got the following error all the cases 

raise RegistrationRejectedException('Unable to verify origin.')
webauthn.webauthn.RegistrationRejectedException: Unable to verify origin. 

In the webauthn_test.py file, I change the RPID and origin to 
RP_ID = 'localhost'
ORIGIN = 'https://localhost:5000' Respectively. 

But still unable to complete the tests. ??

**Comment by futureimperfect** [comment] 2019-08-08 21:45
Hi @afridi26,

Thanks for the feedback. How are you running the tests?

When I run the tests from the root of the repository as follows they pass:

```
$ python3 -m unittest tests/webauthn_test.py
......
----------------------------------------------------------------------
Ran 6 tests in 0.031s

OK
```

Also, out of curiosity, why are you changing the`ORIGIN` and `RP_ID` in the test file?

Thanks!

**Comment by futureimperfect** [comment] 2019-08-09 20:21
Just for additional context, this is expected to fail if you change the values for `RP_ID` and `ORIGIN`, since they're in the mock responses. I'm going to close this for now since it's expected behavior, but if I'm missing something or if you're having trouble running the tests as-is feel free to reopen. Thanks!

**Closed by futureimperfect** 2019-08-09 20:21 UTC
